# The name of the work flow. Badges will use this name
name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build ThisIsWin11
      run: |
        $env:PLATFORM="Any CPU"
        msbuild src\TIW11.sln /p:Configuration="Release" /p:Platform="Any CPU" -verbosity:diag
    - uses: actions/upload-artifact@v3
      with:
        name: WNW11
        path: |
          *
          if-no-files-found: error
